### ISSUE TITLE
Forum Discussion board

### ISSUE THREAD

**Issue by geoff-maddock** [geoff-maddock/events-tracker#151]
Build a full featured forum / discussion board.

# Hierarchy
Forum
  Category
   Thread
    Post

Features
- [x] Create threads
- [ ] Create private threads
- [x] Relate to:  Event, Series, Tag, Entity
- [ ] Allow @mention 
- [x] User notifications
- [ ] Embedding outside content (soundcloud iframe etc)

**Comment by geoff-maddock** [comment]
Closing - none of the additional features are needed yet.   The basics of the forum work fine.
