### ISSUE TITLE
Notification > Media Targets?

### ISSUE THREAD

**Issue by geoff-maddock** [geoff-maddock/events-tracker#906]
Create a notification that can be configured with emails of media members.
Once a week, submit a list of events to those emails with a concisely formatted list of events that have been added in the past week

Targets:
WRCT
City Paper
Post Gazette
Tribune Review
etc

**Comment by geoff-maddock** [comment]
Rework what this would look like.
I would need to add these as entities with a specific type and contact info.
How would I flag what to send to them?

**Comment by geoff-maddock** [comment]
## Implementation Notes

**Approach:**
- Add a new contact type (e.g. `media`) to the contacts system
- The weekly digest notification will query all contacts with the `media` type and send to their emails
- No separate admin UI needed — managing recipients is done via the contacts system

**Email format:** HTML

**To-do before implementation:**
- [ ] Research and compile the initial list of media contacts (WRCT, City Paper, Post Gazette, Tribune Review, etc.)
- [ ] Add `media` as a contact type
- [ ] Build the weekly digest email template (HTML) listing events added in the past week
- [ ] Wire up a scheduled job to send to all media-type contacts
